before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.2
before_script:
 - "curl https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.2.0 bash"
 - "cp config/database.travis.yml config/database.yml"
 - "sed /AWS_HOST/d config/application.example.yml >config/application.yml"
 - "cp config/paypal.example.yml config/paypal.yml"
 - "cp config/secrets.ci.yml config/secrets.yml"
 - "mkdir -p private/elfinder"
 - "RAILS_ENV=test bundle exec rake db:setup --trace"
 - bundle exec sidekiq -d -L /tmp/sidekiq.log
 - sleep 1
after_failure: "cat log/test.log"
services:
 - redis-server
script: RAILS_ENV=test DISPLAY=:99.0 bundle exec rspec --tag ~ci_ignore
notifications:
  recipients:
    - coorasse@gmail.com

