#encoding: utf-8
FACEBOOK_APP_ID: ""
GOOGLE_APP_ID: ""
TWITTER_APP_ID: ""
MEETUP_APP_ID: ""
LINKEDIN_APP_ID: ""
PARMA_APP_ID: ""

MAPS_API_KEY: ""

FACEBOOK_APP_SECRET: ""
GOOGLE_APP_SECRET: ""
TWITTER_APP_SECRET: ""
MEETUP_APP_SECRET: ""
LINKEDIN_APP_SECRET: ""
PARMA_APP_SECRET: ""

EMAIL_ADDRESS: ""
EMAIL_USERNAME: ""
EMAIL_PASSWORD: ""

RECAPTCHA_PUBLIC: ""
RECAPTCHA_PRIVATE: ""

GEOSPATIAL_NAME: ""

APP_SHORT_NAME: "Airesis"
APP_LONG_NAME: "Airesis - Scegli di partecipare"
APP_EMAIL_ADDRESS: "info@example.com"

NEWSLETTER_FROM_ADDRESS: ""
NEWSLETTER_TWITTER_URL: ""
NEWSLETTER_FACEBOOK_URL: ""
NEWSLETTER_GOOGLEPLUS_URL: ""
NEWSLETTER_PREFERENCES_URL: ""
NEWSLETTER_HOME_URL: ""

ERROR_SENDER: ""

#can also be a list of addresses separated by comma
ERROR_RECEIVER: ""

MAILER_DEFAULT_HOST: "www.airesis.eu"

BUGTRACKING_URL: ""
BUGTRACKING_USERNAME: ""
BUGTRACKING_PASSWORD: ""

DEVISE_SECRET_KEY: ""

CROWDIN_API: ""
CROWDIN_PROJECT_ID: ""
CROWDIN_ACCOUNT_KEY: ""

REDIS_URL: "redis://127.0.0.1:6379/12"

SITE: "http://www.airesis.eu"


CAP_STAGING_USER: ""
CAP_STAGING_SERVER: ""
