#encoding: utf-8
#####################
#social networks and services keys
#####################

FACEBOOK_APP_ID: ""
GOOGLE_APP_ID: ""
TWITTER_APP_ID: ""
MEETUP_APP_ID: ""
LINKEDIN_APP_ID: ""
PARMA_APP_ID: ""

MAPS_API_KEY: ""

FACEBOOK_APP_SECRET: ""
GOOGLE_APP_SECRET: ""
TWITTER_APP_SECRET: ""
MEETUP_APP_SECRET: ""
LINKEDIN_APP_SECRET: ""
PARMA_APP_SECRET: ""

RECAPTCHA_PUBLIC: ""
RECAPTCHA_PRIVATE: ""

GEOSPATIAL_NAME: ""

#####################
#email service
#####################

EMAIL_ADDRESS: ""
EMAIL_USERNAME: ""
EMAIL_PASSWORD: ""

MAILER_DEFAULT_HOST: "www.airesis.eu"

#####################
#newsletter parameters
#####################

NEWSLETTER_FROM_ADDRESS: ""
NEWSLETTER_TWITTER_URL: ""
NEWSLETTER_FACEBOOK_URL: ""
NEWSLETTER_GOOGLEPLUS_URL: ""
NEWSLETTER_PREFERENCES_URL: ""
NEWSLETTER_HOME_URL: ""

#####################
# feedbacks (optional)
# set these values to send and receive feedbacks from users
#####################
FEEDBACK_SENDER: "Feedback <feedback@example.com>"
FEEDBACK_RECEIVER: "help@example.com"

#####################
# email settings (required)
# email addresses for all email services
#####################
DEFAULT_FROM: "App <info@example.com>"
NOREPLY_EMAIL: "No Reply <noreply@example.com>"

#####################
#redmine integration (optional)
#####################

BUGTRACKING_URL: ""
BUGTRACKING_USERNAME: ""
BUGTRACKING_PASSWORD: ""

#####################
#application parameters
#####################

APP_SHORT_NAME: "Airesis"
APP_LONG_NAME: "Airesis - Scegli di partecipare"
APP_EMAIL_ADDRESS: "info@example.com"
SITE: "http://www.airesis.eu"
ADMIN_EMAIL: "youremail@example.com"
ADMIN_PASSWORD: "password"

DEVISE_SECRET_KEY: ""

REDIS_URL: "redis://127.0.0.1:6379/12"

AWS_BUCKET: ""
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
AWS_HOSTNAME: ""

#####################
#crowdin integration (optional)
#####################

CROWDIN_API: ""
CROWDIN_PROJECT_ID: ""
CROWDIN_ACCOUNT_KEY: ""

#####################
#capistrano settings (optional)
#####################

CAP_STAGING_USER: ""
CAP_STAGING_SERVER: ""


##############
#sentry settings. remove these keys to not use it (leaving them empty will throw an error)
#############

SENTRY_PUBLIC_KEY: ""
SENTRY_PRIVATE_KEY: ""
SENTRY_PORT: ""

#############
# environment constants (leave default values for default behaviour, change them to change platform behaviour)
#############

#percentage of active users on the platform. this number is used to calculate quorums in the open space only
#the calculation is quorum.percentage * (users * ACTIVE_USER_PERCENTAGE)
#if you have 100 registered users and a 50% quorum the number of valutations and votes is 50 (0.5 * (100 * 1)).
#if you change this value to 30, then the number of valutations and votes will be 15 (0.5 * (100 * 0.3)).
#if you change this value to 10, then the number of valutations and votes will be 5 (0.5 * (100 * 0.1)).
#this is useful to provide accessible quorums in the open space. maybe one day will not be necessary
ACTIVE_USERS_PERCENTAGE: "100"
