defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: postgres
  password: postgres
  host: localhost
  port: 5432

  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: localhost

development:
  database: airesis_development
  <<: *defaults

test:
  database: airesis_test
  <<: *defaults

production:
  database: airesis_production
  <<: *defaults
