calculate_ranking:
  cron: "0 * * * *"
  class: CalculateRankings
  queue: cron
  description: "Aggiorna i ranking degli utenti"

update_sitemap:
  cron: "0 1 * * *"
  class: UpdateSitemap
  queue: cron
  description: "Aggiorna la sitemap del sito"

#change_proposal_state:
#  cron: "0 1 * * *"
#  class: ChangeProposalState
#  queue: cron
#  description: "Aggiorna lo stato delle proposte"
  
delete_old_notifications:
  cron: "0 1 * * *"
  class: DeleteOldNotifications
  queue: cron
  description: "Cancella le vecchie notifiche già lette"