:concurrency: 30
:pidfile: tmp/pids/sidekiq.pid
test:
  :concurrency: 5
production:
  :concurrency: 20
:queues:
  - [high_priority,5]
  - [sunspot,4]
  - [notifications,3]
  - [default,2]
  - [low_priority, 1]
  - [mailers, 1]
