production:
  auto_index_callback: after_commit
  auto_remove_callback: after_commit

development:
  solr:
    log_level: INFO
  auto_index_callback: after_commit
  auto_remove_callback: after_commit

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/test
  auto_index_callback: after_commit
  auto_remove_callback: after_commit
