production:
  solr:
    hostname: 46.101.242.225
    port: 8983
    log_level: WARNING
    path: '/solr/collection1'
    user: admin
    password: airesis

development:
  solr:
    hostname: 46.101.242.225
    port: 8983
    log_level: WARNING
    path: '/solr/collection1'
    user: admin
    password: airesis

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
